name: Manual Trigger

on:
  workflow_dispatch:
    inputs:
      runner:
        required: true
        description: '選択ランナー'
        default: 'ubuntu-latest'
 
jobs:
  ex1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - run: |
        echo "runner: ${{ github.event.inputs.runner }}"
        df --total
        
