name: Manual Trigger

on: [ workflow_dispatch ]

jobs:
  ex1:
    runs-on: ubuntu-latest

    steps:
    - run: |
        echo ====ls run====
        ls
        echo ====whoami run====
        whoami
        echo ====printenv run====
        printenv
        
